server:
    port: 8888
eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://localhost:8888/eureka/
    server:
        enable-self-preservation: false
spring:
    freemarker:
        prefer-file-system-access: false
    cloud:
        config:
            enabled: false
